"use client";
import { useState } from "react";
import Link from "next/link";
import { BadgeEuro, BedDouble, CalendarDays, Car, Check, ChevronDown, Home, Map, MapPin, PawPrint, Search, SlidersHorizontal, Sparkles, Star, Users, Waves, Wifi } from "lucide-react";

const rapides=[[Waves,"Bord de mer"],[Wifi,"Wifi"],[Car,"Parking"],[PawPrint,"Animaux"],[BadgeEuro,"Prix Juste"]];
const annonces=[
 {nom:"Villa des Pins",ville:"Arcachon",prix:149,ancien:159,note:4.9,chambres:3,tags:["Piscine","Wifi","Parking"],juste:true},
 {nom:"Maison du Bassin",ville:"Cap Ferret",prix:189,ancien:200,note:4.8,chambres:4,tags:["Terrasse","Wifi","Plage"],juste:true},
 {nom:"Appartement vue mer",ville:"La Rochelle",prix:118,ancien:118,note:4.7,chambres:2,tags:["Vue mer","Wifi"],juste:false},
];
export default function RechercheV2(){
 const [plus,setPlus]=useState(false); const [carte,setCarte]=useState(false); const [actifs,setActifs]=useState(["Prix Juste"]);
 const toggle=x=>setActifs(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 return <main className="min-h-screen bg-[#F8F4EC] text-[#173C3A]"><header className="border-b border-[#E8DECA] bg-[#FFFDF8]"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/demo" className="font-serif text-xl">Escale</Link><span className="rounded-full bg-[#F1E7D6] px-3 py-1.5 text-xs font-semibold text-[#8D5B30]">Recherche V2 · démo</span></div></header>
 <section className="border-b border-[#E8DECA] bg-[#FFFDF8]"><div className="mx-auto max-w-7xl px-5 py-7"><div className="grid gap-2 rounded-2xl border border-[#E2D6C2] bg-[#F8F4EC] p-2 md:grid-cols-[1.4fr_1fr_.8fr_auto]"><label className="rounded-xl bg-white p-3"><small className="text-[#8D5B30]">OÙ ?</small><div className="mt-1 flex gap-2"><MapPin size={16}/><input className="w-full outline-none" placeholder="Ville, région, bord de mer..."/></div></label><button className="rounded-xl bg-white p-3 text-left"><small className="text-[#8D5B30]">QUAND ?</small><div className="mt-1 flex gap-2 text-sm"><CalendarDays size={16}/>Dates flexibles</div></button><button className="rounded-xl bg-white p-3 text-left"><small className="text-[#8D5B30]">QUI ?</small><div className="mt-1 flex gap-2 text-sm"><Users size={16}/>2 voyageurs</div></button><button className="flex items-center justify-center gap-2 rounded-xl bg-[#173C3A] px-5 text-white"><Search size={17}/>Rechercher</button></div>
 <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{rapides.map(([I,x])=><button key={x} onClick={()=>toggle(x)} className={`flex shrink-0 items-center gap-2 rounded-full border px-3 py-2 text-xs ${actifs.includes(x)?"border-[#173C3A] bg-[#173C3A] text-white":"border-[#E2D6C2] bg-white"}`}><I size={14}/>{x}{actifs.includes(x)&&<Check size={12}/>}</button>)}<button onClick={()=>setPlus(!plus)} className="flex shrink-0 items-center gap-2 rounded-full border border-[#CCB999] bg-white px-3 py-2 text-xs"><SlidersHorizontal size={14}/>Tous les filtres<ChevronDown size={13}/></button></div>
 {plus&&<div className="mt-4 grid gap-3 rounded-2xl border border-[#E2D6C2] bg-white p-5 sm:grid-cols-2 lg:grid-cols-4">{[[BedDouble,"Chambres","2+"],[BadgeEuro,"Budget total","600 € max"],[Home,"Type","Maison"],[Sparkles,"Équipements","Piscine, clim..."]].map(([I,t,v])=><button key={t} className="rounded-xl bg-[#F8F4EC] p-4 text-left"><I size={17}/><p className="mt-2 text-xs text-[#8D5B30]">{t}</p><p className="text-sm font-medium">{v}</p></button>)}</div>}
 </div></section>
 <section className="mx-auto max-w-7xl px-5 py-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-[#6D6258]">24 séjours correspondent</p><h1 className="font-serif text-3xl">Hébergements à découvrir</h1></div><button onClick={()=>setCarte(!carte)} className="flex items-center gap-2 rounded-xl border border-[#CCB999] bg-white px-4 py-2.5 text-sm"><Map size={16}/>{carte?"Masquer la carte":"Afficher la carte"}</button></div>
 {actifs.length>0&&<div className="mt-4 flex flex-wrap gap-2">{actifs.map(x=><button key={x} onClick={()=>toggle(x)} className="rounded-full bg-[#F1E7D6] px-3 py-1.5 text-xs font-medium text-[#8D5B30]">{x} ×</button>)}</div>}
 <div className={`mt-6 grid gap-6 ${carte?"lg:grid-cols-[1.15fr_.85fr]":""}`}><div className="grid gap-5 md:grid-cols-2">{annonces.map(a=><article key={a.nom} className="overflow-hidden rounded-2xl border border-[#E2D6C2] bg-[#FFFDF8]"><div className="relative aspect-[4/3] bg-[#EDE4D4]"><div className="absolute inset-0 grid place-items-center"><Home size={32} className="text-[#B0A48F]"/></div><div className="absolute left-3 top-3 flex gap-2">{a.juste&&<span className="rounded-full bg-[#F1E7D6] px-2.5 py-1 text-[11px] font-semibold text-[#8D5B30]">Prix Juste Escale</span>}<span className="rounded-full bg-white/95 px-2.5 py-1 text-[11px]">Photos 1/8</span></div></div><div className="p-5"><div className="flex justify-between"><div><p className="text-xs text-[#8D5B30]">{a.ville}</p><h2 className="mt-1 font-semibold">{a.nom}</h2></div><span className="flex gap-1 text-sm"><Star size={14}/>{a.note}</span></div><div className="mt-3 flex flex-wrap gap-2">{a.tags.map(t=><span key={t} className="rounded-full bg-[#F8F4EC] px-2.5 py-1 text-[11px]">{t}</span>)}</div><div className="mt-4 flex items-end justify-between"><div><b className="text-lg">{a.prix} €</b><span className="text-xs text-[#6D6258]"> / nuit</span>{a.ancien>a.prix&&<><span className="ml-2 text-sm text-[#8C7A66] line-through">{a.ancien} €</span><p className="text-xs font-semibold text-[#A86735]">Économie {(a.ancien-a.prix)*3} € sur 3 nuits</p></>}</div><button className="rounded-xl bg-[#173C3A] px-3 py-2 text-xs text-white">Voir</button></div></div></article>)}</div>{carte&&<aside className="sticky top-5 hidden h-[620px] rounded-3xl border border-[#E2D6C2] bg-[#E5E1D6] p-5 lg:block"><p className="text-xs uppercase tracking-wider text-[#8D5B30]">Carte synchronisée · démo</p><div className="mt-5 grid h-[530px] place-items-center rounded-2xl border border-dashed border-[#B9AD99]"><div className="text-center"><Map size={32} className="mx-auto"/><p className="mt-2 text-sm">Les prix et logements sélectionnés apparaîtront ici.</p></div></div></aside>}</div>
 </section></main>;
}
