"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BedDouble, CalendarDays, CheckCircle2, CreditCard, RotateCcw, ShieldCheck, Users } from "lucide-react";

const listings = [
  { id: 1, title: "Villa des Embruns", city: "La Rochelle", price: 245, guests: 6, bedrooms: 3, tag: "Maison · bord de mer" },
  { id: 2, title: "Loft Vieux-Port", city: "Marseille", price: 175, guests: 4, bedrooms: 2, tag: "Appartement · centre-ville" },
  { id: 3, title: "Studio Bellecour", city: "Lyon", price: 120, guests: 2, bedrooms: 1, tag: "Studio · hypercentre" },
];

const steps = ["Explorer", "Logement", "Réserver", "Compte", "Paiement", "Confirmation"];
const money = (n) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(n);

export default function DemoPage() {
  const [mode, setMode] = useState("voyageur");
  const [step, setStep] = useState(0);
  const [selected, setSelected] = useState(listings[0]);
  const [nights, setNights] = useState(4);
  const [guests, setGuests] = useState(2);
  const [name, setName] = useState("Alexandre Démo");
  const [email, setEmail] = useState("alexandre.demo@escale.fr");
  const [paid, setPaid] = useState(false);

  const pricing = useMemo(() => {
    const stay = selected.price * nights;
    const cleaning = selected.id === 1 ? 85 : selected.id === 2 ? 65 : 45;
    const tax = guests * nights * 2;
    const total = stay + cleaning + tax;
    const competitor = Math.round(total * 1.12);
    return { stay, cleaning, tax, total, competitor, saving: competitor - total };
  }, [selected, nights, guests]);

  const reset = () => { setMode("voyageur"); setStep(0); setSelected(listings[0]); setNights(4); setGuests(2); setPaid(false); };
  const choose = (l) => { setSelected(l); setStep(1); };

  return <main className="min-h-screen bg-[#F8F4EC] text-[#173C3A]">
    <div className="sticky top-0 z-50 border-b border-amber-300 bg-amber-100 px-4 py-2 text-center text-sm font-semibold text-amber-950">MODE DÉMONSTRATION · aucune réservation ni aucun paiement réel</div>
    <header className="border-b border-[#E6DCCB] bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><div className="flex items-center gap-3"><Link href="/" className="grid h-10 w-10 place-items-center rounded-xl bg-[#173C3A] font-serif text-lg text-[#D99054]">E</Link><div><p className="font-serif text-xl">Escale</p><p className="text-xs text-[#756A60]">Démo interactive</p></div></div><div className="flex gap-2"><button onClick={() => setMode("voyageur")} className={`rounded-xl px-4 py-2 text-sm font-medium ${mode === "voyageur" ? "bg-[#173C3A] text-white" : "border border-[#D8CBB8] bg-white"}`}>Voyageur</button><button onClick={() => setMode("hote")} className={`rounded-xl px-4 py-2 text-sm font-medium ${mode === "hote" ? "bg-[#173C3A] text-white" : "border border-[#D8CBB8] bg-white"}`}>Hôte</button><button onClick={reset} className="rounded-xl border border-[#D8CBB8] bg-white p-2" title="Réinitialiser"><RotateCcw size={18}/></button></div></div></header>

    {mode === "hote" ? <HostDemo paid={paid} selected={selected} pricing={pricing} name={name} /> : <>
      <div className="mx-auto max-w-7xl px-5 pt-6"><div className="grid grid-cols-6 gap-2">{steps.map((s, i) => <div key={s}><div className={`h-1.5 rounded-full ${i <= step ? "bg-[#A86735]" : "bg-[#E8DECE]"}`}/><p className={`mt-2 hidden text-xs sm:block ${i === step ? "font-semibold" : "text-[#887B70]"}`}>{s}</p></div>)}</div></div>

      {step === 0 && <section className="mx-auto max-w-7xl px-5 py-10"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#A86735]">Tester comme un vrai voyageur</p><h1 className="mt-3 max-w-3xl font-serif text-4xl md:text-5xl">Choisissez un logement de démonstration.</h1><p className="mt-4 max-w-2xl text-[#6D6258]">Parcourez une réservation complète jusqu’au paiement simulé, sans créer de vraie transaction.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{listings.map(l => <article key={l.id} className="rounded-3xl border border-[#E0D4C1] bg-white p-6 shadow-sm"><div className="grid h-44 place-items-center rounded-2xl bg-gradient-to-br from-[#D9E4DF] to-[#F0DFC9]"><span className="font-serif text-5xl text-[#173C3A]/70">{l.city.charAt(0)}</span></div><p className="mt-5 text-xs uppercase tracking-wider text-[#9A673D]">{l.city}</p><h2 className="mt-2 text-xl font-semibold">{l.title}</h2><p className="mt-1 text-sm text-[#756A60]">{l.tag}</p><div className="mt-4 flex gap-4 text-sm text-[#756A60]"><span className="flex gap-1"><Users size={16}/>{l.guests}</span><span className="flex gap-1"><BedDouble size={16}/>{l.bedrooms}</span></div><div className="mt-5 flex items-end justify-between"><div><b className="text-xl">{money(l.price)}</b><span className="text-sm text-[#756A60]"> / nuit</span></div><button onClick={() => choose(l)} className="rounded-xl bg-[#173C3A] px-4 py-2.5 text-sm font-medium text-white">Voir <ArrowRight className="ml-1 inline" size={15}/></button></div></article>)}</div></section>}

      {step === 1 && <section className="mx-auto grid max-w-7xl gap-8 px-5 py-10 lg:grid-cols-[1.2fr_.8fr]"><div><button onClick={() => setStep(0)} className="mb-5 flex items-center gap-2 text-sm text-[#756A60]"><ArrowLeft size={16}/> Retour</button><div className="grid h-[420px] place-items-center rounded-3xl bg-gradient-to-br from-[#D9E4DF] to-[#F0DFC9]"><span className="font-serif text-8xl text-[#173C3A]/60">{selected.city.charAt(0)}</span></div><p className="mt-6 text-sm font-semibold uppercase tracking-wider text-[#A86735]">{selected.city}</p><h1 className="mt-2 font-serif text-4xl">{selected.title}</h1><p className="mt-3 text-[#6D6258]">Un logement de démonstration Escale avec disponibilité instantanée, contrat automatique et paiement simulé.</p><div className="mt-6 flex gap-5 text-sm"><span className="flex gap-2"><Users size={17}/>{selected.guests} voyageurs</span><span className="flex gap-2"><BedDouble size={17}/>{selected.bedrooms} chambres</span><span className="flex gap-2"><ShieldCheck size={17}/> Charte Escale</span></div></div><aside className="h-fit rounded-3xl border border-[#DDCFBA] bg-white p-6 shadow-sm"><p><b className="text-2xl">{money(selected.price)}</b> / nuit</p><div className="mt-5 rounded-2xl border border-[#E4D9C8] p-4"><p className="text-sm font-semibold">Disponible pour la démo</p><p className="mt-1 text-sm text-[#756A60]">Dates fictives, aucune disponibilité réelle bloquée.</p></div><button onClick={() => setStep(2)} className="mt-5 w-full rounded-xl bg-[#173C3A] px-5 py-3 font-semibold text-white">Réserver ce logement</button></aside></section>}

      {step === 2 && <Panel title="Votre séjour" subtitle="Choisissez les paramètres de la fausse réservation."><div className="grid gap-4 sm:grid-cols-2"><label className="rounded-2xl border bg-white p-4"><span className="text-sm font-medium">Nombre de nuits</span><input type="number" min="1" max="14" value={nights} onChange={e=>setNights(Math.max(1, Number(e.target.value)))} className="mt-2 w-full rounded-xl border p-3"/></label><label className="rounded-2xl border bg-white p-4"><span className="text-sm font-medium">Voyageurs</span><input type="number" min="1" max={selected.guests} value={guests} onChange={e=>setGuests(Math.max(1, Number(e.target.value)))} className="mt-2 w-full rounded-xl border p-3"/></label></div><PriceBox pricing={pricing} nights={nights} price={selected.price}/><Next onBack={()=>setStep(1)} onNext={()=>setStep(3)} label="Continuer vers le compte"/></Panel>}

      {step === 3 && <Panel title="Création de compte démo" subtitle="Ces informations servent uniquement au scénario affiché à l’écran."><div className="grid gap-4"><label><span className="text-sm font-medium">Nom</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border bg-white p-3"/></label><label><span className="text-sm font-medium">E-mail</span><input value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border bg-white p-3"/></label></div><Next onBack={()=>setStep(2)} onNext={()=>setStep(4)} label="Créer le compte démo"/></Panel>}

      {step === 4 && <Panel title="Paiement simulé" subtitle="Aucune donnée bancaire n’est demandée et aucun prestataire de paiement n’est appelé."><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-900"><ShieldCheck className="mr-2 inline" size={18}/> Environnement de démonstration sécurisé.</div><div className="mt-5 rounded-2xl border bg-white p-5"><div className="flex items-center gap-2 font-semibold"><CreditCard size={19}/> Simulation du paiement</div><p className="mt-2 text-sm text-[#756A60]">Le bouton ci-dessous reproduit uniquement le résultat d’un paiement accepté pour tester la suite du parcours.</p></div><PriceBox pricing={pricing} nights={nights} price={selected.price}/><Next onBack={()=>setStep(3)} onNext={()=>{setPaid(true);setStep(5)}} label={`Simuler le paiement de ${money(pricing.total)}`}/></Panel>}

      {step === 5 && <section className="mx-auto max-w-3xl px-5 py-16 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={60}/><p className="mt-5 text-sm font-semibold uppercase tracking-wider text-emerald-700">Paiement simulé accepté</p><h1 className="mt-3 font-serif text-4xl">Réservation de démonstration confirmée.</h1><p className="mx-auto mt-4 max-w-xl text-[#6D6258]">{name}, votre séjour fictif à {selected.title} est confirmé pour {nights} nuits. Le tableau de bord hôte affiche maintenant cette réservation et le contact CRM.</p><div className="mt-7 rounded-3xl border bg-white p-6 text-left"><p className="text-sm text-[#756A60]">Référence</p><p className="font-mono font-semibold">ESCALE-DEMO-260821</p><div className="mt-4 flex justify-between"><span>Total simulé</span><b>{money(pricing.total)}</b></div><div className="mt-2 flex justify-between text-emerald-700"><span>Économie estimée vs plateforme classique</span><b>{money(pricing.saving)}</b></div></div><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={()=>setMode("hote")} className="rounded-xl bg-[#173C3A] px-5 py-3 font-semibold text-white">Voir côté hôte <ArrowRight className="ml-1 inline" size={16}/></button><button onClick={reset} className="rounded-xl border border-[#CCBDA5] bg-white px-5 py-3 font-semibold">Recommencer la démo</button></div></section>}
    </>}
  </main>;
}

function Panel({title, subtitle, children}) { return <section className="mx-auto max-w-3xl px-5 py-12"><h1 className="font-serif text-4xl">{title}</h1><p className="mt-3 text-[#6D6258]">{subtitle}</p><div className="mt-7">{children}</div></section> }
function Next({onBack,onNext,label}) { return <div className="mt-7 flex justify-between gap-3"><button onClick={onBack} className="rounded-xl border border-[#CCBDA5] bg-white px-4 py-3"><ArrowLeft className="mr-1 inline" size={16}/> Retour</button><button onClick={onNext} className="rounded-xl bg-[#173C3A] px-5 py-3 font-semibold text-white">{label} <ArrowRight className="ml-1 inline" size={16}/></button></div> }
function PriceBox({pricing,nights,price}) { return <div className="mt-5 rounded-2xl border bg-white p-5 text-sm"><div className="flex justify-between"><span>{money(price)} × {nights} nuits</span><span>{money(pricing.stay)}</span></div><div className="mt-2 flex justify-between"><span>Ménage</span><span>{money(pricing.cleaning)}</span></div><div className="mt-2 flex justify-between"><span>Taxe de séjour simulée</span><span>{money(pricing.tax)}</span></div><div className="mt-4 flex justify-between border-t pt-4 text-base font-semibold"><span>Total</span><span>{money(pricing.total)}</span></div><div className="mt-2 flex justify-between text-emerald-700"><span>Économie estimée</span><b>{money(pricing.saving)}</b></div></div> }
function HostDemo({paid,selected,pricing,name}) { return <section className="mx-auto max-w-7xl px-5 py-10"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#A86735]">Vue hôte</p><h1 className="mt-3 font-serif text-4xl">Tableau de bord de démonstration</h1><p className="mt-3 text-[#6D6258]">La réservation créée côté voyageur apparaît ici immédiatement dans la démo.</p><div className="mt-8 grid gap-4 md:grid-cols-4">{[["Réservations","7"],["CA démo","6 380 €"],["Contacts CRM","4"],["Paiements","6"]].map(([l,v])=><div key={l} className="rounded-2xl border bg-white p-5"><p className="text-sm text-[#756A60]">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-2 font-semibold"><CalendarDays size={19}/> Réservation la plus récente</div>{paid ? <div className="mt-5 rounded-2xl bg-[#F8F4EC] p-5"><p className="font-semibold">{selected.title}</p><p className="mt-1 text-sm text-[#756A60]">Voyageur : {name}</p><p className="mt-1 text-sm text-[#756A60]">Montant : {money(pricing.total)}</p><span className="mt-3 inline-block rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800">Confirmée · paiement simulé réussi</span></div> : <p className="mt-5 text-sm text-[#756A60]">Effectuez d’abord une réservation côté voyageur pour la voir ici.</p>}</div><div className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-2 font-semibold"><Users size={19}/> CRM voyageur</div><div className="mt-5 space-y-3">{["Camille Martin · VIP · Famille","Thomas Renard · Fidèle","Julie Bernard · Nouveau client", paid ? `${name} · Nouveau client démo` : "Nora Petit · Prospect"].map(x=><div key={x} className="rounded-xl bg-[#F8F4EC] p-3 text-sm">{x}</div>)}</div></div></div><div className="mt-8 rounded-3xl bg-[#173C3A] p-6 text-white"><h2 className="text-xl font-semibold">Fonctions validables dans cette démo</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Recherche logement","Création compte voyageur","Paiement simulé","Remontée réservation + CRM"].map(x=><div key={x} className="rounded-xl bg-white/10 p-4 text-sm">✓ {x}</div>)}</div></div></section> }
