"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { BadgeEuro, Home, MapPin, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function RecherchePrixJuste() {
 const [logements,setLogements]=useState([]); const [chargement,setChargement]=useState(true);
 useEffect(()=>{async function charger(){const supabase=createClient(); const {data}=await supabase.from("listings").select("id,title,city,price_per_night,guests,average_rating,fair_price_charter").eq("status","actif").eq("fair_price_charter",true).order("created_at",{ascending:false}); setLogements(data??[]); setChargement(false)} charger()},[]);
 return <main className="min-h-screen bg-[#F8F4EC] px-5 py-10 text-[#173C3A]"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/recherche" className="text-sm text-[#6D6258]">← Tous les logements</Link><Link href="/charte-prix-juste" className="text-sm font-medium text-[#A86735]">Comprendre la Charte</Link></div><div className="mt-8 max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full bg-[#E1EEE9] px-3 py-1.5 text-xs font-semibold"><BadgeEuro size={14}/> Filtre actif : Prix Juste Escale</div><h1 className="mt-4 font-serif text-4xl">Les hôtes engagés pour un prix plus juste.</h1><p className="mt-3 leading-7 text-[#6D6258]">Ces annonces portent l’engagement déclaré de leur hôte : proposer sur Escale un tarif au moins 5 % plus avantageux que sur les plateformes traditionnelles, à conditions comparables.</p></div>{chargement?<p className="mt-10 text-sm">Chargement…</p>:logements.length===0?<div className="mt-10 rounded-2xl border border-[#E2D6C2] bg-white/60 p-7"><ShieldCheck className="text-[#A86735]"/><h2 className="mt-3 text-xl font-semibold">Les premières annonces engagées arriveront ici.</h2><p className="mt-2 text-sm text-[#6D6258]">Le filtre est prêt. Les annonces apparaîtront dès que leurs hôtes auront activé la Charte.</p></div>:<div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{logements.map(l=><Link key={l.id} href={`/logement/${l.id}`} className="overflow-hidden rounded-2xl border border-[#E2D6C2] bg-[#FFFDF8]"><div className="flex aspect-[4/3] items-center justify-center bg-[#EDE4D4]"><Home className="text-[#B0A48F]"/></div><div className="p-5"><div className="inline-flex items-center gap-1 rounded-full bg-[#E1EEE9] px-2.5 py-1 text-xs font-semibold">✓ Prix Juste Escale</div><h2 className="mt-3 font-semibold">{l.title}</h2><p className="mt-1 flex items-center gap-1 text-sm text-[#6D6258]"><MapPin size={13}/>{l.city}</p><p className="mt-3 font-semibold">{Number(l.price_per_night)} € <span className="text-xs font-normal text-[#6D6258]">/ nuit</span></p></div></Link>)}</div>}</div></main>
}
