import Link from "next/link";
import { redirect, notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

const euro=c=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format((c||0)/100);
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"}):"—";

export default async function ReservationCrmPage({params}){
 const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect(`/connexion?suite=/hote/crm/reservations/${params.id}`);
 const {data:r}=await supabase.from("reservations").select("id,listing_id,guest_id,guest_first_name,start_date,end_date,guests,amount_total,status,has_open_dispute,tourist_tax_amount,deposit_status,deposit_amount").eq("id",params.id).maybeSingle(); if(!r) notFound();
 const {data:listing}=await supabase.from("listings").select("id,title,city,host_id").eq("id",r.listing_id).eq("host_id",user.id).maybeSingle(); if(!listing) notFound();
 const [{data:payment},{data:guest},{data:docs}]=await Promise.all([
  supabase.from("payments").select("id,status,amount_total,amount_host,platform_fee,partner_fee,tourist_tax_held,payment_provider,payment_channel,transferred_at,partner_transferred_at,payout_last_error").eq("reservation_id",r.id).maybeSingle(),
  r.guest_id?supabase.from("profiles").select("id,full_name,email").eq("id",r.guest_id).maybeSingle():Promise.resolve({data:null}),
  supabase.from("reservation_documents").select("id,title,document_type,status,created_at").eq("reservation_id",r.id).eq("host_id",user.id).order("created_at",{ascending:false})
 ]);
 const steps=[['Réservation',true],['Paiement',payment?.status==='succeeded'],['Séjour commencé',new Date()>=new Date(`${r.start_date}T00:00:00`)],['Séjour terminé',new Date()>=new Date(`${r.end_date}T23:59:59`)],['Reversement',!!payment?.transferred_at]];
 return <main className="min-h-screen bg-[#F7F5F0] p-5 md:p-8"><div className="mx-auto max-w-5xl"><Link href="/hote/crm" className="text-sm text-[#2F6E6E]">← CRM</Link><div className="mt-3"><h1 className="text-3xl font-semibold text-[#1B3A3A]">Réservation 360°</h1><p className="text-stone-500">{listing.title} • {listing.city||''}</p></div>
 <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-5"><div className="grid gap-4 md:grid-cols-5">{steps.map(([label,ok])=><div key={label}><div className={`h-2 rounded-full ${ok?'bg-[#2F6E6E]':'bg-stone-200'}`}></div><p className="mt-2 text-xs font-medium">{label}</p></div>)}</div></section>
 <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-stone-200 bg-white p-5"><h2 className="font-semibold text-lg">Séjour</h2><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Voyageur</span><b>{guest?.full_name||r.guest_first_name||'Voyageur'}</b></div><div className="flex justify-between"><span>Email</span><span>{guest?.email||'—'}</span></div><div className="flex justify-between"><span>Dates</span><b>{fmt(r.start_date)} → {fmt(r.end_date)}</b></div><div className="flex justify-between"><span>Voyageurs</span><span>{r.guests}</span></div><div className="flex justify-between"><span>Total</span><b>{euro(r.amount_total)}</b></div><div className="flex justify-between"><span>Statut</span><span>{r.status}</span></div>{r.has_open_dispute&&<div className="rounded-xl bg-red-50 p-3 text-red-700">⚠ Litige ouvert : reversement suspendu.</div>}</div></div>
 <div className="rounded-2xl border border-stone-200 bg-white p-5"><h2 className="font-semibold text-lg">Paiement</h2>{payment?<div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Canal</span><b>{payment.payment_provider} • {payment.payment_channel}</b></div><div className="flex justify-between"><span>Net hôte</span><b>{euro(payment.amount_host)}</b></div><div className="flex justify-between"><span>Commission ESCALE</span><span>{euro(payment.platform_fee)}</span></div><div className="flex justify-between"><span>Conciergerie</span><span>{euro(payment.partner_fee)}</span></div><div className="flex justify-between"><span>Taxe de séjour isolée</span><span>{euro(payment.tourist_tax_held)}</span></div><div className="flex justify-between"><span>Reversement</span><b>{payment.transferred_at?'Effectué ✓':'En attente'}</b></div>{payment.payout_last_error&&<div className="rounded-xl bg-amber-50 p-3 text-amber-800">{payment.payout_last_error}</div>}</div>:<p className="mt-4 text-sm text-stone-400">Aucun paiement enregistré.</p>}</div></section>
 <section className="mt-5 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="font-semibold text-lg">Documents</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{(docs||[]).map(d=><div key={d.id} className="rounded-xl bg-[#F7F5F0] p-3"><b>{d.title}</b><p className="text-xs text-stone-500">{d.document_type} • {d.status}</p></div>)}{!(docs||[]).length&&<p className="text-sm text-stone-400">Aucun document rattaché à cette réservation pour le moment.</p>}</div></section>
 </div></main>;
}
