"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function ExpenseForm({ listings=[] }){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function submit(e){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const body={listingId:f.get("listingId")||null,category:f.get("category"),label:f.get("label"),amount:Number(f.get("amount")),expenseDate:f.get("expenseDate"),recurring:f.get("recurring")==="on",recurrence:f.get("recurrence")||null,notes:f.get("notes")};const res=await fetch("/api/hote/crm/expenses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!res.ok){const d=await res.json().catch(()=>({}));setError(d.error||"Impossible d'ajouter la charge");setBusy(false);return;}e.currentTarget.reset();setBusy(false);router.refresh();}
 return <form onSubmit={submit} className="grid gap-3 md:grid-cols-2"><input name="label" required placeholder="Libellé de la charge" className="rounded-xl border border-stone-200 px-3 py-2"/><select name="category" required className="rounded-xl border border-stone-200 px-3 py-2"><option value="">Catégorie</option><option>Ménage</option><option>Énergie</option><option>Assurance</option><option>Entretien</option><option>Copropriété</option><option>Fiscalité</option><option>Autre</option></select><input name="amount" required type="number" min="0" step="0.01" placeholder="Montant €" className="rounded-xl border border-stone-200 px-3 py-2"/><input name="expenseDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="rounded-xl border border-stone-200 px-3 py-2"/><select name="listingId" className="rounded-xl border border-stone-200 px-3 py-2"><option value="">Tous les logements / global</option>{listings.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select><input name="notes" placeholder="Note facultative" className="rounded-xl border border-stone-200 px-3 py-2"/><label className="flex items-center gap-2 text-sm"><input name="recurring" type="checkbox"/> Charge récurrente</label><select name="recurrence" className="rounded-xl border border-stone-200 px-3 py-2"><option value="">Fréquence</option><option value="mensuelle">Mensuelle</option><option value="trimestrielle">Trimestrielle</option><option value="annuelle">Annuelle</option></select><div className="md:col-span-2"><button disabled={busy} className="rounded-xl bg-[#1B3A3A] px-4 py-2 text-white text-sm font-medium">{busy?"Ajout…":"Ajouter la charge"}</button>{error&&<span className="ml-3 text-sm text-red-700">{error}</span>}</div></form>;
}
