"use client";

import React, { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BarChart3, BadgePercent, Check, ChevronDown, FileText, Menu, MessageCircle, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { COMMISSION_RATE_TTC, SUBSCRIPTION_FEE_TTC, SUBSCRIPTION_RATE_TTC, formatEuros, formatTaux } from "@/lib/pricing";

const essentielTools = ["Publication et visibilité sur Escale", "Réservations issues d’Escale ou de vos propres voyageurs", "Paiement sécurisé et suivi des reversements", "Contrat personnalisable généré automatiquement", "Calendrier et synchronisation des disponibilités", "Messagerie directe avec le voyageur", "Options, caution et règles définies par l’hôte", "Tableau de bord de réservation"];
const proTools = ["Tout Escale Essentiel", "CRM voyageurs et historique client 360°", "Import de contacts issus d’autres canaux", "Segmentation clients : fidèle, VIP, famille, pro…", "Campagnes et offres promotionnelles", "Relances et scénarios de fidélisation", "Codes promotionnels et offres ciblées", "Pilotage du chiffre d’affaires et de la rentabilité", "Automatisations avancées et contrats conditionnels"];
const faq = [
 {q:"Quelle est la vraie différence entre Essentiel et Pro ?",r:"Essentiel vous permet de louer simplement, sans abonnement, que le voyageur vous découvre sur Escale ou qu’il vienne de votre propre réseau. Pro ajoute les outils pour construire, connaître et fidéliser votre clientèle dans le temps."},
 {q:"Le contrat personnalisable est-il réservé à Pro ?",r:"Non. Le contrat personnalisable fait partie du cœur d’Escale et est disponible dans les deux offres. Pro ajoute surtout des modèles multiples, des clauses conditionnelles et davantage d’automatisation."},
 {q:"Qu’est-ce que la Charte du Prix Juste Escale ?",r:"Escale encourage les hôtes à partager une partie de l’économie réalisée sur les frais de plateforme avec leurs voyageurs. L’objectif est de proposer un prix final plus attractif tout en préservant, lorsque la configuration tarifaire le permet, un revenu net hôte compétitif."},
 {q:"Puis-je ajouter dans le CRM des voyageurs connus ailleurs ?",r:"Oui, Pro est pensé pour centraliser votre portefeuille client, y compris des contacts provenant d’autres canaux, dans le respect des consentements et règles applicables."},
 {q:"Essentiel peut-il m’apporter de nouveaux voyageurs ?",r:"Oui. Essentiel n’est pas limité aux réservations que vous apportez vous-même : votre logement peut aussi être découvert et réservé par les visiteurs d’Escale."}
];
const euros=v=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(v);

export default function LandingPage(){
 const [menuOpen,setMenuOpen]=useState(false),[faqOpen,setFaqOpen]=useState(0),[nightlyRate,setNightlyRate]=useState(150),[nights,setNights]=useState(1),[competitorRate,setCompetitorRate]=useState(15),[travelerDiscount,setTravelerDiscount]=useState(5),[formula,setFormula]=useState("essentiel");
 const simulation=useMemo(()=>{const competitorGross=nightlyRate*nights,escaleGross=competitorGross*(1-travelerDiscount/100),competitorNet=competitorGross*(1-competitorRate/100),essentielNet=escaleGross*(1-COMMISSION_RATE_TTC),proNet=escaleGross*(1-SUBSCRIPTION_RATE_TTC),selectedNet=formula==="pro"?proNet:essentielNet;return{competitorGross,escaleGross,competitorNet,selectedNet,travelerSaving:competitorGross-escaleGross,hostGain:selectedNet-competitorNet}},[nightlyRate,nights,competitorRate,travelerDiscount,formula]);
 return <main className="min-h-screen bg-[#F8F4EC] text-[#173C3A]">
  <header className="sticky top-0 z-40 border-b border-[#E8DECA] bg-[#F8F4EC]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 font-serif text-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#173C3A] text-[#D99054]">E</span>Escale</Link><nav className="hidden items-center gap-7 text-sm text-[#6D6258] md:flex"><a href="#pourquoi">Pourquoi Escale ?</a><a href="#prix-juste">Prix juste</a><a href="#offres">Nos offres</a><a href="#pro">Escale Pro</a><a href="#simulateur">Simulateur</a></nav><div className="hidden items-center gap-3 md:flex"><Link href="/connexion" className="text-sm text-[#6D6258]">Se connecter</Link><Link href="/hote" className="rounded-xl bg-[#173C3A] px-4 py-2.5 text-sm font-medium text-white">Devenir hôte</Link></div><button className="md:hidden" onClick={()=>setMenuOpen(v=>!v)} aria-label="Menu">{menuOpen?<X/>:<Menu/>}</button></div>{menuOpen&&<div className="border-t px-5 py-4 md:hidden"><div className="flex flex-col gap-3"><a href="#pourquoi">Pourquoi Escale ?</a><a href="#prix-juste">Prix juste</a><a href="#offres">Nos offres</a><a href="#pro">Escale Pro</a><a href="#simulateur">Simulateur</a></div></div>}</header>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 py-16 md:grid-cols-[1.08fr_.92fr] md:py-24"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#DFCDB0] bg-[#F2E9DA] px-3 py-1.5 text-xs font-medium uppercase tracking-[.15em] text-[#8D5B30]"><Sparkles size={13}/> Une solution qui s’adapte à votre façon de louer</div><h1 className="max-w-3xl font-serif text-5xl leading-[1.04] md:text-6xl">Louez simplement. <span className="text-[#A86735]">Développez votre activité si vous le souhaitez.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#6D6258]">Escale met en relation hôtes et voyageurs et fournit les outils pour réserver, sécuriser et gérer vos locations. Profitez des voyageurs qui découvrent votre logement sur Escale, accueillez vos propres contacts et, avec Pro, transformez progressivement vos voyageurs en clientèle fidèle.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#essentiel" className="inline-flex items-center gap-2 rounded-xl bg-[#173C3A] px-5 py-3 font-medium text-white">Je veux louer simplement <ArrowRight size={16}/></a><a href="#pro" className="rounded-xl border border-[#CCB999] px-5 py-3 font-medium">Je veux fidéliser ma clientèle</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-[#6D6258]"><span className="flex gap-2"><ShieldCheck size={16}/> Paiement sécurisé</span><span className="flex gap-2"><FileText size={16}/> Contrat personnalisable</span><span className="flex gap-2"><BadgePercent size={16}/> Prix voyageur plus attractif</span></div></div>
   <div className="rounded-3xl bg-[#173C3A] p-7 text-white"><p className="text-sm text-[#C8D8D4]">ESCALE PRO</p><h2 className="mt-2 text-2xl font-semibold">Ne vous contentez plus d’accueillir vos voyageurs. Faites-les revenir.</h2><p className="mt-4 leading-7 text-[#C8D8D4]">Chaque séjour peut enrichir votre connaissance client et devenir le point de départ d’une prochaine réservation.</p><div className="mt-7 grid grid-cols-2 gap-3">{[["Clients CRM","148"],["Voyageurs fidèles","37"],["Offres à relancer","12"],["CA fidélisé","8 420 €"]].map(([l,v])=><div key={l} className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-[#BFD0CD]">{l}</p><p className="mt-2 text-xl font-semibold">{v}</p></div>)}</div></div></section>
  <section id="pourquoi" className="border-y border-[#E8DECA] bg-white/45 py-16"><div className="mx-auto max-w-7xl px-5"><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Pourquoi Escale ?</p><h2 className="mt-3 max-w-3xl font-serif text-4xl">Un canal d’acquisition, un outil de réservation et, avec Pro, un outil de fidélisation.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{[[Users,"Être découvert sur Escale","Votre logement peut être trouvé par les voyageurs qui visitent la plateforme."],[ShieldCheck,"Accueillir vos propres voyageurs","Utilisez Escale pour cadrer la réservation, le paiement et le contrat, quelle que soit l’origine du contact."],[BarChart3,"Faire revenir avec Pro","Construisez votre base clients et animez-la avec des offres, des segments et des relances."]].map(([I,t,d])=><article key={t} className="rounded-2xl border border-[#E2D6C2] bg-[#FBF8F2] p-5"><I className="text-[#A86735]"/><h3 className="mt-4 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#6D6258]">{d}</p></article>)}</div></div></section>
  <section id="prix-juste" className="bg-[#F1E7D6] py-16"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.9fr_1.1fr]"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3 py-1.5 text-xs font-medium uppercase tracking-[.15em] text-[#8D5B30]"><BadgePercent size={14}/> Charte du Prix Juste Escale</div><h2 className="mt-4 font-serif text-4xl">Moins de frais pour l’hôte. Un meilleur prix pour le voyageur.</h2><p className="mt-4 leading-7 text-[#6D6258]">Escale encourage les hôtes à partager une partie de l’économie réalisée sur les frais de plateforme. Le but n’est pas de casser les prix : c’est de créer un meilleur équilibre entre le prix payé par le voyageur et le revenu conservé par l’hôte.</p><a href="#simulateur" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#173C3A] px-5 py-3 font-medium text-white">Tester avec mon tarif <ArrowRight size={16}/></a></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-white p-6"><p className="text-xs uppercase tracking-wider text-[#8D5B30]">Côté voyageur</p><h3 className="mt-3 text-2xl font-semibold">Le même séjour, à un prix plus juste.</h3><p className="mt-3 leading-7 text-[#6D6258]">Les hôtes sont invités à proposer sur Escale un tarif plus attractif que sur les plateformes traditionnelles, par exemple 5 % inférieur lorsque leur économie le permet.</p><div className="mt-5 rounded-2xl bg-[#F8F4EC] p-4"><p className="text-sm text-[#6D6258]">Exemple</p><p className="mt-2">Ailleurs : <b>500 €</b></p><p>Escale : <b>475 €</b></p><p className="mt-2 font-semibold text-[#A86735]">Voyageur : 25 € économisés</p></div></div><div className="rounded-3xl bg-[#173C3A] p-6 text-white"><p className="text-xs uppercase tracking-wider text-[#C8D8D4]">Côté hôte</p><h3 className="mt-3 text-2xl font-semibold">Soyez moins cher sans gagner moins.</h3><p className="mt-3 leading-7 text-[#C8D8D4]">Une baisse du prix public peut rester compatible avec une meilleure marge nette lorsque les frais de plateforme sont plus faibles.</p><div className="mt-5 rounded-2xl bg-white/10 p-4"><p className="text-sm text-[#C8D8D4]">Exemple indicatif</p><p className="mt-2">Plateforme à 15 % sur 500 € : <b>425 € nets</b></p><p>Escale Essentiel sur 475 € : <b>≈ 437 € nets</b></p><p className="mt-2 font-semibold text-[#D99054]">Hôte : ≈ 12 € de plus</p></div></div></div></div></section>
  <section id="offres" className="mx-auto max-w-7xl px-5 py-16"><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Deux ambitions, deux solutions</p><h2 className="mt-3 font-serif text-4xl">Commencez simplement. Passez à Pro quand la fidélisation devient un levier.</h2><div className="mt-10 grid gap-6 lg:grid-cols-2"><article id="essentiel" className="rounded-3xl border border-[#DCCFB8] bg-[#FBF8F2] p-7"><p className="text-sm text-[#6D6258]">ESCALE ESSENTIEL</p><h3 className="mt-3 text-2xl font-semibold">Louez simplement, à votre rythme.</h3><div className="mt-4"><span className="text-5xl font-semibold">{formatTaux(COMMISSION_RATE_TTC)}</span> TTC / réservation</div><p className="mt-3 text-[#6D6258]">Sans abonnement. Accueillez les voyageurs apportés par Escale ou vos propres contacts avec tous les outils nécessaires pour gérer la réservation.</p><ul className="mt-6 space-y-3">{essentielTools.map(x=><li key={x} className="flex gap-2"><Check size={18} className="mt-0.5 shrink-0 text-[#A86735]"/>{x}</li>)}</ul><div className="mt-6 rounded-2xl bg-[#F1E7D6] p-4 text-sm"><b>Prix Juste conseillé :</b> partagez une partie de votre économie de frais avec le voyageur pour rendre votre annonce plus compétitive.</div><Link href="/hote" className="mt-8 block rounded-xl border border-[#BFAF92] px-4 py-3 text-center font-medium">Commencer sans abonnement</Link></article><article id="pro" className="rounded-3xl bg-[#173C3A] p-7 text-white"><p className="text-sm text-[#C8D8D4]">ESCALE PRO</p><h3 className="mt-3 text-2xl font-semibold">Transformez vos voyageurs en clients fidèles.</h3><div className="mt-4"><span className="text-5xl font-semibold">{formatTaux(SUBSCRIPTION_RATE_TTC)}</span> TTC + {formatEuros(SUBSCRIPTION_FEE_TTC)}/mois</div><p className="mt-3 text-[#C8D8D4]">Tout Essentiel, plus la boîte à outils commerciale pour connaître vos voyageurs, les relancer et générer de nouvelles réservations.</p><ul className="mt-6 space-y-3">{proTools.map(x=><li key={x} className="flex gap-2"><Check size={18} className="mt-0.5 shrink-0 text-[#D99054]"/>{x}</li>)}</ul><Link href="/hote" className="mt-8 block rounded-xl bg-[#D99054] px-4 py-3 text-center font-medium">Développer ma clientèle</Link></article></div></section>
  <section className="bg-[#173C3A] py-16 text-white"><div className="mx-auto max-w-7xl px-5"><h2 className="font-serif text-4xl">Avec Pro, chaque nouveau voyageur peut devenir un futur client fidèle.</h2><div className="mt-9 grid gap-3 md:grid-cols-5">{["1. Il réserve","2. Vous l’accueillez","3. Il enrichit votre CRM","4. Vous le relancez","5. Il revient"].map(x=><div key={x} className="rounded-2xl bg-white/10 p-5 font-medium">{x}</div>)}</div></div></section>
  <section id="simulateur" className="mx-auto max-w-7xl px-5 py-16"><div className="inline-flex items-center gap-2 rounded-full bg-[#F1E7D6] px-3 py-1.5 text-xs font-medium uppercase tracking-[.15em] text-[#8D5B30]"><BadgePercent size={14}/> Preuve chiffrée du Prix Juste</div><h2 className="mt-4 font-serif text-4xl">Combien pouvez-vous conserver de plus ?</h2><p className="mt-3 text-[#6D6258]">Testez dès une nuitée. Le simulateur compare votre plateforme actuelle à l’offre Escale choisie, en tenant compte d’un prix voyageur plus attractif.</p><div className="mt-8 grid gap-8 lg:grid-cols-2"><div className="space-y-5 rounded-3xl border border-[#E2D6C2] bg-white/50 p-6"><label className="block">Prix de la nuitée ailleurs : <b>{euros(nightlyRate)}</b><input className="mt-2 w-full" type="range" min="50" max="1000" step="10" value={nightlyRate} onChange={e=>setNightlyRate(+e.target.value)}/></label><div className="flex gap-2">{[1,3,7].map(n=><button key={n} onClick={()=>setNights(n)} className={`rounded-xl px-4 py-2 ${nights===n?"bg-[#173C3A] text-white":"border"}`}>{n} nuit{n>1?"s":""}</button>)}</div><label className="block">Frais plateforme actuelle : <b>{competitorRate}%</b><input className="mt-2 w-full" type="range" min="10" max="20" value={competitorRate} onChange={e=>setCompetitorRate(+e.target.value)}/></label><label className="block">Remise voyageur sur Escale : <b>{travelerDiscount}%</b><input className="mt-2 w-full" type="range" min="0" max="10" value={travelerDiscount} onChange={e=>setTravelerDiscount(+e.target.value)}/></label><div className="flex gap-2"><button onClick={()=>setFormula("essentiel")} className={`rounded-xl px-4 py-2 ${formula==="essentiel"?"bg-[#173C3A] text-white":"border"}`}>Essentiel</button><button onClick={()=>setFormula("pro")} className={`rounded-xl px-4 py-2 ${formula==="pro"?"bg-[#173C3A] text-white":"border"}`}>Pro</button></div></div><div className="rounded-3xl bg-[#F1E7D6] p-7"><p>Prix ailleurs : <b>{euros(simulation.competitorGross)}</b></p><p className="mt-2">Prix voyageur Escale : <b>{euros(simulation.escaleGross)}</b></p><p className="mt-2">Économie voyageur : <b>{euros(simulation.travelerSaving)}</b></p><div className="my-5 border-t border-[#D8C6A8]"/><p>Net hôte ailleurs : <b>{euros(simulation.competitorNet)}</b></p><p className="mt-2">Net hôte Escale : <b>{euros(simulation.selectedNet)}</b></p><p className="mt-5 text-xl font-semibold">{simulation.hostGain>=0?`Vous conservez ${euros(simulation.hostGain)} de plus sur cette réservation.`:`Écart : ${euros(simulation.hostGain)}. Ajustez la remise pour préserver votre marge.`}</p><p className="mt-4 text-xs leading-5 text-[#6D6258]">Simulation indicative. Les frais des plateformes concurrentes varient selon leurs conditions. L’abonnement mensuel Pro n’est pas imputé à une seule réservation.</p></div></div></section>
  <section className="border-t border-[#E8DECA] py-16"><div className="mx-auto max-w-4xl px-5"><h2 className="font-serif text-4xl">Questions fréquentes</h2><div className="mt-7 space-y-3">{faq.map((f,i)=><div key={f.q} className="rounded-2xl border border-[#E2D6C2] bg-[#FBF8F2]"><button className="flex w-full items-center justify-between p-5 text-left font-medium" onClick={()=>setFaqOpen(faqOpen===i?-1:i)}>{f.q}<ChevronDown size={18}/></button>{faqOpen===i&&<p className="px-5 pb-5 leading-7 text-[#6D6258]">{f.r}</p>}</div>)}</div></div></section>
  <footer className="bg-[#102F2D] py-10 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 md:flex-row"><div><p className="font-serif text-2xl">Escale</p><p className="mt-2 text-sm text-[#B8CBC7]">Moins de frais. Un prix plus juste. Une relation plus directe.</p></div><div className="flex gap-5 text-sm text-[#B8CBC7]"><Link href="/cgu">CGU</Link><Link href="/confidentialite">Confidentialité</Link><Link href="/contact">Contact</Link></div></div></footer>
 </main>;
}
