import Link from "next/link";
import { ArrowRight, BadgeEuro, CalendarDays, Check, FileCheck2, FileText, Heart, LockKeyhole, MapPin, MessageCircle, Search, ShieldCheck, Sparkles, Star, Users, Wallet } from "lucide-react";

const demoListings = [
 {title:"Villa des Oliviers",place:"Luberon, Provence",guests:6,rating:"4,9",oldPrice:210,price:199,image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85"},
 {title:"Maison Océan",place:"Guéthary, Pays basque",guests:5,rating:"4,8",oldPrice:185,price:175,image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85"},
 {title:"Chalet des Cimes",place:"Chamonix, Haute-Savoie",guests:8,rating:"5,0",oldPrice:265,price:249,image:"https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1000&q=85"},
 {title:"Bergerie du Maquis",place:"Porto-Vecchio, Corse",guests:4,rating:"4,9",oldPrice:230,price:218,image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85"}
];

export default function VoyageursPage(){return <main className="min-h-screen bg-[#F8F4EC] text-[#173C3A]">
<header className="sticky top-0 z-40 border-b border-[#E8DECA] bg-[#F8F4EC]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 font-serif text-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#173C3A] text-[#D99054]">E</span>Escale</Link><nav className="hidden gap-6 text-sm text-[#6D6258] md:flex"><a href="#escales">Explorer</a><a href="#prix-juste">Prix Juste</a><a href="#confiance">Votre sécurité</a></nav><div className="flex items-center gap-4 text-sm"><Link href="/" className="hidden sm:block">Je suis hôte</Link><Link href="/connexion" className="rounded-xl bg-[#173C3A] px-4 py-2.5 text-white">Se connecter</Link></div></div></header>

<section className="mx-auto max-w-7xl px-5 pb-10 pt-14 md:pt-18"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-[#DFCDB0] bg-[#F2E9DA] px-3 py-1.5 text-xs font-medium uppercase tracking-[.15em] text-[#8D5B30]"><Sparkles size={13}/> Le Prix Juste Escale</div><h1 className="mt-5 font-serif text-5xl leading-[1.03] md:text-6xl">Le même séjour. <span className="text-[#A86735]">Un prix plus juste.</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#6D6258]">Trouvez votre logement, réservez dans un cadre sécurisé et profitez de tarifs que les hôtes sont encouragés à rendre plus attractifs grâce au modèle Escale.</p></div>
<div className="mt-8 grid gap-3 rounded-3xl border border-[#E2D6C2] bg-white p-3 shadow-sm md:grid-cols-[1.3fr_1fr_1fr_auto]"><div className="rounded-2xl bg-[#F8F4EC] p-4"><p className="text-xs uppercase tracking-wider text-[#8D5B30]">Destination</p><div className="mt-1 flex items-center gap-2"><MapPin size={17}/> Où voulez-vous partir ?</div></div><div className="rounded-2xl bg-[#F8F4EC] p-4"><p className="text-xs uppercase tracking-wider text-[#8D5B30]">Dates</p><div className="mt-1 flex items-center gap-2"><CalendarDays size={17}/> Ajouter des dates</div></div><div className="rounded-2xl bg-[#F8F4EC] p-4"><p className="text-xs uppercase tracking-wider text-[#8D5B30]">Voyageurs</p><div className="mt-1 flex items-center gap-2"><Users size={17}/> 2 voyageurs</div></div><Link href="/recherche" className="flex items-center justify-center gap-2 rounded-2xl bg-[#173C3A] px-6 py-4 font-medium text-white"><Search size={18}/> Rechercher</Link></div>
<div className="mt-5 flex flex-wrap gap-5 text-sm text-[#6D6258]"><span className="flex gap-2"><LockKeyhole size={16}/> Paiement sécurisé</span><span className="flex gap-2"><FileText size={16}/> Contrat de réservation</span><span className="flex gap-2"><BadgeEuro size={16}/> Prix clair avant paiement</span><span className="flex gap-2"><MessageCircle size={16}/> Échange avec l’hôte</span></div></section>

<section id="escales" className="mx-auto max-w-7xl px-5 py-12"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Quelques Escales pour s’inspirer</p><h2 className="mt-2 font-serif text-4xl">Et si vous partiez bientôt ?</h2></div><p className="max-w-md text-sm leading-6 text-[#6D6258]">Sélection fictive destinée à illustrer l’expérience Escale.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{demoListings.map(item=>{const saving=item.oldPrice-item.price;return <article key={item.title} className="group"><div className="relative h-52 overflow-hidden rounded-2xl bg-[#E9E1D4]"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><button aria-label="Ajouter aux favoris" className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/95 shadow"><Heart size={17}/></button><span className="absolute bottom-3 left-3 rounded-full bg-white/95 px-3 py-1.5 text-xs font-semibold">✓ Prix Juste</span></div><div className="pt-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-[#6D6258]">{item.place}</p></div><span className="flex items-center gap-1 text-sm"><Star size={14} fill="currentColor"/> {item.rating}</span></div><p className="mt-2 text-sm text-[#6D6258]">{item.guests} voyageurs</p><div className="mt-3"><span className="mr-2 text-sm text-[#8A7C70] line-through">{item.oldPrice} €</span><span className="font-semibold">{item.price} € / nuit</span></div><p className="mt-1 text-sm font-medium text-[#A86735]">Vous économisez {saving} € / nuit</p></div></article>})}</div><div className="mt-8 text-center"><Link href="/recherche" className="inline-flex items-center gap-2 rounded-xl border border-[#CDBD9E] px-5 py-3 font-medium">Explorer les logements <ArrowRight size={16}/></Link></div></section>

<section id="prix-juste" className="border-y border-[#E8DECA] bg-[#F1E7D6] py-16"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Le Prix Juste Escale</p><h2 className="mt-3 font-serif text-4xl">Pourquoi payer davantage pour le même séjour ?</h2><p className="mt-4 max-w-2xl leading-7 text-[#6D6258]">Escale fonctionne avec des frais plus légers et encourage les hôtes à partager une partie de cette économie avec leurs voyageurs. L’objectif : un tarif plus compétitif pour vous, sans obliger l’hôte à sacrifier sa marge.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/70 p-5"><BadgeEuro className="text-[#A86735]"/><h3 className="mt-3 font-semibold">Un prix plus attractif</h3><p className="mt-2 text-sm leading-6 text-[#6D6258]">Les hôtes sont encouragés à proposer un meilleur tarif Escale lorsque leur économie le permet.</p></div><div className="rounded-2xl bg-white/70 p-5"><Wallet className="text-[#A86735]"/><h3 className="mt-3 font-semibold">Pas de surprise au paiement</h3><p className="mt-2 text-sm leading-6 text-[#6D6258]">Le prix de votre réservation doit être présenté clairement avant votre engagement.</p></div></div></div><div className="rounded-3xl bg-[#173C3A] p-7 text-white"><p className="text-sm text-[#C8D8D4]">EXEMPLE PRIX JUSTE</p><div className="mt-6 grid gap-3"><div className="rounded-2xl bg-white/10 p-5"><p className="text-sm text-[#C8D8D4]">Même séjour sur un autre canal</p><p className="mt-1 text-3xl font-semibold">500 €</p></div><div className="rounded-2xl bg-[#D99054] p-5"><p className="text-sm">Exemple sur Escale</p><p className="mt-1 text-3xl font-semibold">475 €</p></div></div><p className="mt-5 text-xl font-semibold">25 € restent dans votre budget vacances.</p><p className="mt-3 text-xs leading-5 text-[#C8D8D4]">Exemple pédagogique. Le tarif réel dépend de l’hôte, des dates et des conditions du séjour.</p></div></div></section>

<section id="confiance" className="mx-auto max-w-7xl px-5 py-16"><div className="max-w-3xl"><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Votre réservation, notre cadre</p><h2 className="mt-3 font-serif text-4xl">Réservez directement. Pas sans protection.</h2><p className="mt-4 text-lg leading-8 text-[#6D6258]">Escale facilite la mise en relation avec l’hôte tout en encadrant les étapes essentielles de la réservation. Vous savez avec qui vous réservez, ce que vous payez et dans quelles conditions.</p></div><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[LockKeyhole,"Paiement sécurisé","Votre règlement passe par le parcours de paiement Escale et son fonctionnement est présenté avant validation."],[FileCheck2,"Réservation contractualisée","Les conditions du séjour sont formalisées dans un contrat lié à votre réservation."],[BadgeEuro,"Prix transparent","Le montant et les éléments tarifaires sont affichés avant votre engagement, sans frais ajoutés discrètement à la dernière étape."],[MessageCircle,"Relation avec l’hôte","Vous pouvez échanger avec la personne qui vous accueille et conserver un historique de la conversation."]].map(([Icon,t,d])=><article key={t} className="rounded-2xl border border-[#E2D6C2] bg-white/55 p-6"><Icon className="text-[#A86735]"/><h3 className="mt-4 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#6D6258]">{d}</p></article>)}</div><div className="mt-8 rounded-3xl bg-[#173C3A] p-7 text-white md:flex md:items-center md:justify-between"><div><p className="text-sm text-[#C8D8D4]">LA PHILOSOPHIE ESCALE</p><h3 className="mt-2 text-2xl font-semibold">Plus direct ne veut pas dire moins sécurisé.</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-[#C8D8D4]">Nous voulons conserver la simplicité d’une relation directe entre hôte et voyageur tout en apportant le cadre nécessaire à une réservation sereine.</p></div><ShieldCheck size={48} className="mt-5 shrink-0 text-[#D99054] md:ml-8 md:mt-0"/></div></section>

<section className="bg-[#173C3A] py-14 text-white"><div className="mx-auto max-w-4xl px-5 text-center"><h2 className="font-serif text-4xl">Trouvez votre prochaine Escale.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#C8D8D4]">Un logement qui vous plaît, un prix plus juste et un parcours conçu pour réserver sereinement.</p><Link href="/recherche" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#D99054] px-5 py-3 font-medium">Rechercher un séjour <ArrowRight size={16}/></Link></div></section>
</main>}
