import Link from "next/link";
import { ArrowRight, BadgeEuro, Check, FileText, Heart, Search, ShieldCheck, Sparkles, Star, Wallet } from "lucide-react";

const demoListings = [
  { title: "Villa des Oliviers", place: "Luberon, Provence", guests: 6, rating: "4,9", oldPrice: 210, price: 199, image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85" },
  { title: "Maison Océan", place: "Guéthary, Pays basque", guests: 5, rating: "4,8", oldPrice: 185, price: 175, image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85" },
  { title: "Chalet des Cimes", place: "Chamonix, Haute-Savoie", guests: 8, rating: "5,0", oldPrice: 265, price: 249, image: "https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1000&q=85" },
  { title: "Bergerie du Maquis", place: "Porto-Vecchio, Corse", guests: 4, rating: "4,9", oldPrice: 230, price: 218, image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85" },
];

export default function VoyageursPage() {
 return <main className="min-h-screen bg-[#F8F4EC] text-[#173C3A]">
  <header className="sticky top-0 z-40 border-b border-[#E8DECA] bg-[#F8F4EC]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 font-serif text-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#173C3A] text-[#D99054]">E</span>Escale</Link><nav className="hidden gap-6 text-sm text-[#6D6258] md:flex"><a href="#escales">Explorer</a><a href="#prix-juste">Prix Juste</a><a href="#confiance">Comment ça marche</a></nav><div className="flex items-center gap-4 text-sm"><Link href="/" className="hidden sm:block">Je suis hôte</Link><Link href="/connexion" className="rounded-xl bg-[#173C3A] px-4 py-2.5 text-white">Se connecter</Link></div></div></header>

  <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1.08fr_.92fr] lg:py-20"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#DFCDB0] bg-[#F2E9DA] px-3 py-1.5 text-xs font-medium uppercase tracking-[.15em] text-[#8D5B30]"><Sparkles size={13}/> Le Prix Juste Escale</div><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-[1.04] md:text-6xl">Le même séjour. <span className="text-[#A86735]">Un prix plus juste.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#6D6258]">Escale encourage les hôtes à proposer leurs logements à un prix plus attractif que sur les grandes plateformes, grâce à des frais plus légers. Vous gardez le confort d’une réservation encadrée, avec davantage de budget pour votre séjour.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/recherche" className="inline-flex items-center gap-2 rounded-xl bg-[#173C3A] px-5 py-3 font-medium text-white">Découvrir les logements <ArrowRight size={16}/></Link><a href="#prix-juste" className="rounded-xl border border-[#CCB999] px-5 py-3 font-medium">Pourquoi c’est moins cher ?</a></div><div className="mt-7 flex flex-wrap gap-5 text-sm text-[#6D6258]"><span className="flex gap-2"><ShieldCheck size={16}/> Paiement sécurisé</span><span className="flex gap-2"><FileText size={16}/> Contrat clair</span><span className="flex gap-2"><BadgeEuro size={16}/> Prix Juste Escale</span></div></div><div className="rounded-3xl bg-[#173C3A] p-7 text-white"><p className="text-sm text-[#C8D8D4]">LE PRIX JUSTE EN UN COUP D’ŒIL</p><h2 className="mt-2 text-2xl font-semibold">Moins de frais peuvent devenir un meilleur prix.</h2><div className="mt-7 space-y-3"><div className="rounded-2xl bg-white/10 p-5"><p className="text-sm text-[#BFD0CD]">Prix du même séjour ailleurs</p><p className="mt-1 text-3xl font-semibold">500 €</p></div><div className="rounded-2xl bg-[#D99054] p-5"><p className="text-sm">Exemple de prix Escale</p><p className="mt-1 text-3xl font-semibold">475 €</p></div></div><p className="mt-5 text-xl font-semibold">25 € de plus pour profiter de votre séjour.</p><p className="mt-2 text-xs leading-5 text-[#C8D8D4]">Exemple pédagogique. Chaque hôte reste responsable du tarif réellement proposé.</p></div></section>

  <section id="escales" className="mx-auto max-w-7xl px-5 pb-16"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Quelques Escales pour s’inspirer</p><h2 className="mt-2 font-serif text-4xl">Et si vous partiez bientôt ?</h2></div><p className="max-w-md text-sm leading-6 text-[#6D6258]">Sélection fictive pour illustrer l’expérience de réservation Escale.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{demoListings.map(item=>{const saving=item.oldPrice-item.price;return <article key={item.title} className="group"><div className="relative h-52 overflow-hidden rounded-2xl bg-[#E9E1D4]"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><button aria-label="Ajouter aux favoris" className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/95 shadow"><Heart size={17}/></button><span className="absolute bottom-3 left-3 rounded-full bg-white/95 px-3 py-1.5 text-xs font-semibold">Prix Juste</span></div><div className="pt-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-[#6D6258]">{item.place}</p></div><span className="flex items-center gap-1 text-sm"><Star size={14} fill="currentColor"/> {item.rating}</span></div><p className="mt-2 text-sm text-[#6D6258]">{item.guests} voyageurs</p><div className="mt-3"><span className="mr-2 text-sm text-[#8A7C70] line-through">{item.oldPrice} €</span><span className="font-semibold">{item.price} € / nuit</span></div><p className="mt-1 text-sm font-medium text-[#A86735]">Vous économisez {saving} € / nuit</p></div></article>})}</div><div className="mt-8 text-center"><Link href="/recherche" className="inline-flex items-center gap-2 rounded-xl border border-[#CDBD9E] px-5 py-3 font-medium">Explorer les logements <ArrowRight size={16}/></Link></div></section>

  <section id="prix-juste" className="border-y border-[#E8DECA] bg-[#F1E7D6] py-16"><div className="mx-auto max-w-7xl px-5"><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Pourquoi un meilleur prix est possible</p><h2 className="mt-3 max-w-3xl font-serif text-4xl">L’économie créée par Escale est faite pour être partagée.</h2><p className="mt-4 max-w-3xl leading-7 text-[#6D6258]">Avec des frais plus légers, l’hôte peut proposer un tarif voyageur plus compétitif tout en préservant sa marge. Escale encourage ce cercle vertueux plutôt que d’ajouter des frais au prix final.</p><div className="mt-9 grid gap-4 md:grid-cols-3">{[[BadgeEuro,"Un prix plus attractif","Les hôtes sont encouragés à afficher sur Escale un tarif inférieur à leurs autres canaux lorsque leur économie le permet."],[ShieldCheck,"Une réservation encadrée","Un prix plus doux ne retire pas les éléments de confiance : paiement sécurisé et conditions de séjour restent clairement posés."],[Wallet,"Une économie visible","Le voyageur doit pouvoir comprendre simplement ce qu’il économise, sans décoder une grille de commissions."]].map(([Icon,t,d])=><article key={t} className="rounded-2xl bg-white/70 p-6"><Icon className="text-[#A86735]"/><h3 className="mt-4 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#6D6258]">{d}</p></article>)}</div></div></section>

  <section id="confiance" className="mx-auto max-w-7xl px-5 py-16"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-sm font-medium uppercase tracking-[.15em] text-[#A86735]">Réserver sereinement</p><h2 className="mt-3 font-serif text-4xl">Simple pour réserver. Clair pour partir.</h2><p className="mt-4 leading-7 text-[#6D6258]">Escale privilégie une relation plus directe avec l’hôte, sans sacrifier le cadre dont vous avez besoin pour réserver sereinement.</p></div><div className="grid gap-3">{[[Search,"Trouvez le logement qui correspond à votre séjour."],[FileText,"Consultez les conditions et le contrat associés à la réservation."],[ShieldCheck,"Réglez dans un parcours de paiement sécurisé."],[Check,"Partez en sachant clairement ce qui est inclus et qui vous accueille."]].map(([Icon,t])=><div key={t} className="flex gap-3 rounded-2xl border border-[#E2D6C2] bg-white/50 p-5"><Icon className="shrink-0 text-[#A86735]"/><p>{t}</p></div>)}</div></div></section>

  <section className="bg-[#173C3A] py-14 text-white"><div className="mx-auto max-w-4xl px-5 text-center"><h2 className="font-serif text-4xl">Votre prochaine Escale, au prix juste.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#C8D8D4]">Découvrez les logements et gardez davantage de votre budget pour ce qui compte vraiment : le séjour.</p><Link href="/recherche" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#D99054] px-5 py-3 font-medium">Découvrir les logements <ArrowRight size={16}/></Link></div></section>
 </main>;
}
