import { Home, Search, ShieldCheck, Eye, Star } from "lucide-react";
const rows=[
 ["Villa des Embruns","La Rochelle","245 €","Actif","4,8","38"],
 ["Loft Vieux-Port","Marseille","175 €","Actif","4,6","21"],
 ["Chalet du Lac","Annecy","290 €","À vérifier","4,9","54"],
 ["Maison du Cap","Biarritz","320 €","Actif","4,7","46"],
 ["Studio Presqu’île","Lyon","118 €","Signalé","4,3","17"],
];
export default function AdminLogements(){return <main className="p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-[#2F6E6E]">Catalogue</p><h1 className="font-serif text-3xl">Logements</h1><p className="mt-2 text-sm text-[#6B5B4D]">Publication, qualité, modération et performance des annonces.</p></div><button className="rounded-lg bg-[#173C3A] px-4 py-2.5 text-sm text-white">Exporter</button></div><div className="mt-6 flex items-center gap-2 rounded-xl border border-[#E4DCC8] bg-white px-4 py-3"><Search size={16}/><input className="w-full bg-transparent text-sm outline-none" placeholder="Rechercher par logement, ville ou hôte…"/></div><section className="mt-5 overflow-hidden rounded-2xl border border-[#E4DCC8] bg-white"><div className="grid grid-cols-[1.5fr_1fr_.7fr_.8fr_.6fr_.6fr] gap-3 border-b border-[#E4DCC8] bg-[#FFFDF8] px-5 py-3 text-xs text-[#8C7A66]"><span>Logement</span><span>Ville</span><span>Prix</span><span>Statut</span><span>Note</span><span>Avis</span></div>{rows.map(r=><div key={r[0]} className="grid grid-cols-[1.5fr_1fr_.7fr_.8fr_.6fr_.6fr] gap-3 border-b border-[#EFE8DB] px-5 py-4 text-sm last:border-0"><strong className="flex items-center gap-2"><Home size={14}/>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span><span className="flex items-center gap-1"><Star size={12}/>{r[4]}</span><span>{r[5]}</span></div>)}</section><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["À modérer","7",ShieldCheck],["Vues aujourd’hui","3 842",Eye],["Annonces actives","1 284",Home]].map(([l,v,I])=><div key={l} className="rounded-xl border border-[#E4DCC8] bg-white p-5"><I size={18}/><div className="mt-2 text-2xl font-semibold">{v}</div><div className="text-sm text-[#8C7A66]">{l}</div></div>)}</div></div></main>}
