import { Mail, MousePointerClick, CalendarClock, ShoppingBag, Users } from "lucide-react";

const campagnes=[
  {nom:"Recherche abandonnée",segment:"Voyageurs avec recherche sans réservation",statut:"Active",ouvert:"48 %",clic:"16 %",resa:"7"},
  {nom:"Retour à Biarritz",segment:"Anciens voyageurs Côte basque",statut:"Planifiée",ouvert:"—",clic:"—",resa:"—"},
  {nom:"Bienvenue nouvel hôte",segment:"Hôtes inscrits depuis 7 jours",statut:"Active",ouvert:"62 %",clic:"24 %",resa:"—"},
];

export default function AdminMarketingPage(){return <main className="min-h-screen bg-[#F5F1E8] p-5 text-[#173C3A] md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[#2F6E6E]">Back-office · Growth</p><h1 className="font-serif text-3xl">Email marketing & CRM</h1><p className="mt-2 text-sm text-[#6B5B4D]">Piloter les segments, scénarios et résultats sans sortir du back-office.</p></div><button className="rounded-lg bg-[#173C3A] px-4 py-2.5 text-sm font-medium text-white">Nouvelle campagne</button></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Contacts ciblables","4 280",Users],["Emails envoyés","12 640",Mail],["Taux de clic","14,8 %",MousePointerClick],["Réservations attribuées","86",ShoppingBag]].map(([l,v,I])=><div key={l} className="rounded-xl border border-[#E4DCC8] bg-white p-5"><I size={18}/><div className="mt-3 text-2xl font-semibold">{v}</div><div className="text-sm text-[#8C7A66]">{l}</div></div>)}</div><section className="mt-7 overflow-hidden rounded-2xl border border-[#E4DCC8] bg-white"><div className="flex items-center gap-2 border-b border-[#E4DCC8] p-5"><CalendarClock size={18}/><h2 className="font-serif text-xl">Scénarios</h2></div><div className="divide-y divide-[#EFE8DB]">{campagnes.map(c=><div key={c.nom} className="grid gap-3 p-5 md:grid-cols-[1.5fr_1.5fr_.7fr_.5fr_.5fr_.5fr]"><strong>{c.nom}</strong><span className="text-sm text-[#6B5B4D]">{c.segment}</span><span className="text-sm">{c.statut}</span><span className="text-sm">Ouvert {c.ouvert}</span><span className="text-sm">Clic {c.clic}</span><span className="text-sm">Résa {c.resa}</span></div>)}</div></section></div></main>}
