import Link from "next/link";
import { BadgeEuro, CheckCircle2, Scale, ShieldCheck } from "lucide-react";

export const metadata = { title: "Charte du Prix Juste — Escale", description: "Engagement volontaire des hôtes Escale en faveur d’un tarif plus juste pour les voyageurs." };

export default function ChartePrixJuste() { return <main className="min-h-screen bg-[#F8F4EC] text-[#173C3A] px-5 py-12"><article className="mx-auto max-w-4xl">
<Link href="/voyageurs" className="text-sm text-[#6D6258]">← Retour à Escale</Link>
<div className="mt-8"><div className="inline-flex items-center gap-2 rounded-full bg-[#F1E7D6] px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-[#8D5B30]"><BadgeEuro size={14}/> Engagement Escale</div><h1 className="mt-4 font-serif text-5xl">Charte du Prix Juste Escale</h1><p className="mt-5 text-lg leading-8 text-[#6D6258]">Escale défend une idée simple : lorsque notre modèle permet à l’hôte de supporter moins de frais, une partie de cette économie peut profiter au voyageur. La Charte matérialise cet engagement.</p></div>
<section className="mt-10 space-y-5"><div className="rounded-2xl border border-[#E2D6C2] bg-white/60 p-6"><h2 className="text-xl font-semibold">1. Une adhésion volontaire</h2><p className="mt-2 leading-7 text-[#6D6258]">Chaque hôte reste libre d’adhérer ou non à la Charte pour chacune de ses annonces. L’adhésion est déclarative et peut être retirée depuis l’espace hôte.</p></div><div className="rounded-2xl border border-[#E2D6C2] bg-white/60 p-6"><h2 className="text-xl font-semibold">2. L’engagement des 5 %</h2><p className="mt-2 leading-7 text-[#6D6258]">En adhérant, l’hôte s’engage à proposer sur Escale, pour un même hébergement et à conditions comparables, un tarif au moins 5 % plus avantageux que celui proposé sur les plateformes traditionnelles sur lesquelles il diffuse également son annonce.</p></div><div className="rounded-2xl border border-[#E2D6C2] bg-white/60 p-6"><h2 className="text-xl font-semibold">3. Un badge clairement identifié</h2><p className="mt-2 leading-7 text-[#6D6258]">Tant que l’adhésion est active, l’annonce peut afficher le badge « Prix Juste Escale » et être proposée dans les filtres dédiés. Ce badge traduit l’engagement déclaré de l’hôte. Il ne constitue pas une certification issue d’une comparaison permanente des prix par Escale.</p></div><div className="rounded-2xl border border-[#E2D6C2] bg-white/60 p-6"><h2 className="text-xl font-semibold">4. Conditions comparables</h2><p className="mt-2 leading-7 text-[#6D6258]">La comparaison s’apprécie notamment pour les mêmes dates, le même nombre de voyageurs, le même hébergement et des prestations et conditions de réservation comparables. Les taxes publiques ou options spécifiques peuvent modifier le total final.</p></div><div className="rounded-2xl border border-[#E2D6C2] bg-white/60 p-6"><h2 className="text-xl font-semibold">5. Sincérité de l’engagement</h2><p className="mt-2 leading-7 text-[#6D6258]">L’hôte s’engage à ne pas utiliser le badge de manière trompeuse. En cas de signalements concordants ou de non-respect manifeste et répété, Escale pourra demander des éléments justificatifs et retirer le badge, conformément aux Conditions générales applicables.</p></div><div className="rounded-2xl border border-[#E2D6C2] bg-white/60 p-6"><h2 className="text-xl font-semibold">6. Retrait de l’adhésion</h2><p className="mt-2 leading-7 text-[#6D6258]">L’hôte peut désactiver son adhésion pour l’avenir. Le badge est alors retiré de l’annonce. Les réservations déjà conclues restent régies par les prix et conditions acceptés au moment de leur confirmation.</p></div></section>
<div className="mt-10 grid gap-4 md:grid-cols-3">{[[CheckCircle2,"Simple","Un engagement oui/non, sans niveaux complexes."],[ShieldCheck,"Transparent","Le voyageur sait qu’il s’agit d’un engagement de l’hôte."],[Scale,"Équilibré","L’économie créée vise à profiter à l’hôte comme au voyageur."]].map(([Icon,t,d])=><div key={t} className="rounded-2xl bg-[#173C3A] p-5 text-white"><Icon className="text-[#D99054]"/><h3 className="mt-3 font-semibold">{t}</h3><p className="mt-1 text-sm text-[#C8D8D4]">{d}</p></div>)}</div>
<p className="mt-10 text-xs leading-5 text-[#7C7065]">Document de travail destiné à être annexé aux Conditions générales d’Escale. Il doit être relu et validé par un professionnel du droit avant sa publication comme document opposable.</p>
</article></main> }
