import { Megaphone, Users, Euro, MousePointerClick } from "lucide-react";

const rows=[
 {nom:"Côte Basque Loc",type:"Conciergerie",code:"BASQUE24",clics:842,resa:37,ca:"18 420 €",statut:"Actif"},
 {nom:"Julie Escapades",type:"Créatrice",code:"JULIEESCALE",clics:1260,resa:29,ca:"12 870 €",statut:"Actif"},
 {nom:"Maison & Lac",type:"Partenaire local",code:"LAC10",clics:318,resa:11,ca:"5 940 €",statut:"Actif"},
];

export default function AmbassadeursPage(){return <main className="min-h-screen bg-[#F5F1E8] p-5 text-[#173C3A] md:p-8"><div className="mx-auto max-w-7xl"><div className="flex items-start justify-between"><div><p className="text-sm text-[#2F6E6E]">Back-office · Acquisition</p><h1 className="font-serif text-3xl">Programme ambassadeurs</h1><p className="mt-2 text-sm text-[#6B5B4D]">Suivre les apporteurs, les codes, les réservations et la valeur générée.</p></div><Megaphone size={28}/></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Ambassadeurs actifs","24",Users],["Clics attribués","8 460",MousePointerClick],["CA attribué","74 320 €",Euro]].map(([l,v,I])=><div key={l} className="rounded-xl border border-[#E4DCC8] bg-white p-5"><I size={18}/><div className="mt-3 text-2xl font-semibold">{v}</div><div className="text-sm text-[#8C7A66]">{l}</div></div>)}</div><section className="mt-7 overflow-hidden rounded-2xl border border-[#E4DCC8] bg-white"><div className="grid grid-cols-[1.4fr_1fr_1fr_.7fr_.7fr_1fr_.6fr] gap-3 border-b border-[#E4DCC8] bg-[#FFFDF8] px-5 py-3 text-xs font-medium text-[#8C7A66]"><span>Ambassadeur</span><span>Type</span><span>Code</span><span>Clics</span><span>Résa</span><span>CA</span><span>Statut</span></div>{rows.map(r=><div key={r.code} className="grid grid-cols-[1.4fr_1fr_1fr_.7fr_.7fr_1fr_.6fr] gap-3 border-b border-[#EFE8DB] px-5 py-4 text-sm last:border-b-0"><strong>{r.nom}</strong><span>{r.type}</span><code>{r.code}</code><span>{r.clics}</span><span>{r.resa}</span><span>{r.ca}</span><span>{r.statut}</span></div>)}</section></div></main>}
