import { FlaskConical, ArrowUpRight, ShieldCheck, MousePointer2 } from "lucide-react";

const tests=[
 {nom:"CTA fiche logement",a:"Réserver",b:"Voir mes dates",kpi:"Démarrage réservation",lift:"+8,4 %",etat:"En cours"},
 {nom:"Badge Prix Juste",a:"Badge seul",b:"Badge + économie",kpi:"Clic fiche logement",lift:"+5,1 %",etat:"En cours"},
 {nom:"Preuve de confiance",a:"Paiement sécurisé",b:"Paiement + annulation claire",kpi:"Paiement terminé",lift:"+3,7 %",etat:"Gagnant B"},
];

export default function ExperimentsPage(){return <main className="min-h-screen bg-[#F5F1E8] p-5 text-[#173C3A] md:p-8"><div className="mx-auto max-w-7xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-[#2F6E6E]">Back-office · Conversion</p><h1 className="font-serif text-3xl">Tests A/B et confiance</h1><p className="mt-2 text-sm text-[#6B5B4D]">Expérimenter les CTA et signaux de confiance avec affectation stable par visiteur.</p></div><FlaskConical size={28}/></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Expériences actives","2",FlaskConical],["Uplift moyen","+6,8 %",ArrowUpRight],["Conversions suivies","1 842",MousePointer2]].map(([l,v,I])=><div key={l} className="rounded-xl border border-[#E4DCC8] bg-white p-5"><I size={18}/><div className="mt-3 text-2xl font-semibold">{v}</div><div className="text-sm text-[#8C7A66]">{l}</div></div>)}</div><div className="mt-7 grid gap-4">{tests.map(t=><article key={t.nom} className="rounded-2xl border border-[#E4DCC8] bg-white p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck size={16}/><h2 className="font-serif text-xl">{t.nom}</h2></div><p className="mt-2 text-sm text-[#6B5B4D]">A : {t.a} · B : {t.b}</p><p className="mt-1 text-xs text-[#8C7A66]">KPI : {t.kpi}</p></div><div className="flex items-center gap-5"><div><div className="text-xs text-[#8C7A66]">Résultat</div><strong className="text-lg">{t.lift}</strong></div><span className="rounded-full bg-[#E1EEE9] px-3 py-1 text-xs">{t.etat}</span></div></div></article>)}</div></div></main>}
