import { BrainCircuit, Sparkles, Mail, Target, TrendingUp } from "lucide-react";

const actions=[
 {titre:"Relancer les recherches chaudes",detail:"412 voyageurs avec intention forte mais sans réservation",impact:"Potentiel +38 réservations",icon:Target},
 {titre:"Recommander des logements similaires",detail:"Personnalisation selon villes, budget, capacité et équipements",impact:"Score actif",icon:Sparkles},
 {titre:"Réactiver les anciens voyageurs",detail:"Segment séjour terminé depuis 6 à 18 mois",impact:"1 280 contacts",icon:Mail},
];

export default function GrowthAIPage(){return <main className="min-h-screen bg-[#F5F1E8] p-5 text-[#173C3A] md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-[#2F6E6E]">Back-office · Automatisation</p><h1 className="font-serif text-3xl">IA Growth</h1><p className="mt-2 max-w-2xl text-sm text-[#6B5B4D]">Transformer les signaux de recherche et de réservation en recommandations et campagnes assistées.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-[#E1EEE9] px-3 py-1.5 text-sm"><BrainCircuit size={15}/> Mode recommandation</span></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Profils scorés","3 842",BrainCircuit],["Recommandations servies","11 420",Sparkles],["Conversion assistée","9,6 %",TrendingUp]].map(([l,v,I])=><div key={l} className="rounded-xl border border-[#E4DCC8] bg-white p-5"><I size={18}/><div className="mt-3 text-2xl font-semibold">{v}</div><div className="text-sm text-[#8C7A66]">{l}</div></div>)}</div><section className="mt-7 grid gap-4 lg:grid-cols-3">{actions.map(({titre,detail,impact,icon:Icon})=><article key={titre} className="rounded-2xl border border-[#E4DCC8] bg-white p-6"><Icon size={20}/><h2 className="mt-4 font-serif text-xl">{titre}</h2><p className="mt-2 text-sm text-[#6B5B4D]">{detail}</p><div className="mt-5 rounded-lg bg-[#F8F4EC] px-3 py-2 text-sm font-medium">{impact}</div><button className="mt-4 text-sm font-medium text-[#2F6E6E]">Préparer la campagne →</button></article>)}</section><p className="mt-6 text-xs text-[#8C7A66]">Le scoring est déterministe et explicable. Une couche LLM peut enrichir le texte des campagnes sans décider seule de l’éligibilité d’un utilisateur.</p></div></main>}
